[package]
name = "scenario1"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "tcpserver" , "tcpclient" , "httpserver" , "http"
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
